# Generated by Django 3.0.8 on 2020-07-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
