version: "3.3"

services:
  adminer:
     image: adminer
     restart: always
     ports:
       - "8080:8080"
     env_file:
       - .live.env

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - $HOME/django_app:/app
      - $HOME/data/production_static:/vol/web
    restart: always
    env_file:
      - .live.env

  db:
    restart: always
    user: root
    image: bianjp/mariadb-alpine
    ports:
      - 3306:3306
    volumes:
      - $HOME/data/production_db:/var/lib/mysql
    env_file:
      - .live.env

  redis:
    restart: always
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - $HOME/data/production_redis:/data

  caddy:
    restart: unless-stopped
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $HOME/data/production_static:/srv
      - $HOME/data/caddy_data:/data
      - $HOME/data/caddy_config:/config
    depends_on:
      - app
    env_file:
      - .live.env

volumes:
  production_static:
  production_db:
  production_redis:
  caddy_data:
  caddy_config:
  src:
