version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src:/app
      - ../../data/production_static:/vol/web
    restart: always
    env_file:
      - .live.env
  db:
    restart: always
    user: root
    image: bianjp/mariadb-alpine
    ports:
      - 3306:3306
    volumes:
      - ../../data/production_db:/var/lib/mysql
    env_file:
      - .live.env

  redis:
    restart: always
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ../../data/production_redis:/data

  proxy:
    build:
      context: ./proxy
    user: root
    volumes:
      - ../../data/production_static:/vol/static
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  production_static:
  production_db:
  production_redis:
  src:
