version: "3.3"

services:
  adminer:
     image: adminer
     restart: always
     env_file:
       - .env
     ports:
       - "8080:8080"

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - "${PWD}/django_app:/app"
      - "${DATA_DIR}/production_static:/vol/web"
    restart: always

  db:
    restart: unless-stopped
    user: root
    image: bianjp/mariadb-alpine
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - "${DATA_DIR}/production_db:/var/lib/mysql"

  redis:
    restart: always
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - "${DATA_DIR}/redis_data:/data"

#   caddy:
#     restart: unless-stopped
#     image: caddy:alpine
#     env_file:
#       - .env
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./Caddyfile:/etc/caddy/Caddyfile
#       - "${DATA_DIR}/static:/srv"
#       - "${DATA_DIR}/caddy_data:/data"
#       - "${DATA_DIR}/caddy_config:/config"
#     depends_on:
#       - app

volumes:
  production_static:
  production_db:
  redis_data:
  caddy_data:
  caddy_config:
  django_app:
